package framePkg;

import classPkg_CC.Client;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class ClientPanel extends javax.swing.JPanel {
FileReader fr = null;
    BufferedReader br = null;
    String s = null;
    String n = null;
String name="";
String ido = "";
String ida = "";
Client c = new Client();
    /**
     * Creates new form ClientPanel
     */
    public ClientPanel() {
        initComponents();
    }
   
    
    public void setNameAndID(String id){
        File f = new File("Contract.txt");
        if(f.exists()){
        try {
            fr = new FileReader(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        br = new BufferedReader(fr);
        try {
            while ((s = br.readLine()) != null){
                if(s.contains(id)){
                    n=s;
                    String words[] = n.split(",");
                    ido = words[0];
                     if(id.equals(id)){
                        ida = words[0];
                    name = words[1];
                    c.getID(ida);
                    }                   
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        idLabel.setText(ida);
        nameLabel.setText(name);
        }
        else{
        idLabel.setText("");
        nameLabel.setText("");
        
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeInformationBtn = new javax.swing.JButton();
        feedBackBtn = new javax.swing.JButton();
        contractBtn = new javax.swing.JButton();
        AdditionalStaffBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        renewContractBtn = new javax.swing.JButton();

        employeeInformationBtn.setText("Employee Information");
        employeeInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInformationBtnActionPerformed(evt);
            }
        });

        feedBackBtn.setText("Feedback");
        feedBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedBackBtnActionPerformed(evt);
            }
        });

        contractBtn.setText("CheckContract");
        contractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractBtnActionPerformed(evt);
            }
        });

        AdditionalStaffBtn.setText("Additional Staff or request");
        AdditionalStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionalStaffBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("ID");

        renewContractBtn.setText("Renew Contract ");
        renewContractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewContractBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLabel)
                            .addComponent(nameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(renewContractBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdditionalStaffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(employeeInformationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contractBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(feedBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idLabel)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditionalStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renewContractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdditionalStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionalStaffBtnActionPerformed



 AdditionalStaffRequestForClientFrame f = new AdditionalStaffRequestForClientFrame(ida);
    f.setVisible(true);
    

    }//GEN-LAST:event_AdditionalStaffBtnActionPerformed

    private void feedBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedBackBtnActionPerformed
        // TODO add your handling cod
        FeedbackFrame Fm=new FeedbackFrame();
        Fm.data(ida, name);
        Fm.setVisible(true);
        
    }//GEN-LAST:event_feedBackBtnActionPerformed

    private void employeeInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInformationBtnActionPerformed
        // TODO add your handling code here:
       c.viewEmployeeInfo();
    }//GEN-LAST:event_employeeInformationBtnActionPerformed

    private void contractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractBtnActionPerformed
        // TODO add your handling code here:
     c.checkContract();
        
    }//GEN-LAST:event_contractBtnActionPerformed

    private void renewContractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewContractBtnActionPerformed
        // TODO add your handling code here:
        c.renewContract(ida, name);
        JOptionPane.showMessageDialog(null,"Sent!");
        
        
    }//GEN-LAST:event_renewContractBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionalStaffBtn;
    private javax.swing.JButton contractBtn;
    private javax.swing.JButton employeeInformationBtn;
    private javax.swing.JButton feedBackBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton renewContractBtn;
    // End of variables declaration//GEN-END:variables
}
