package framePkg;
//import classPkg.ClientReport;
import classPkg_CC.ClientReport;
import classPkg_CC.StaffReport;
import java.io.File;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MonthlyClientReportInfoFrame extends javax.swing.JInternalFrame {
        DefaultTableModel model =null;
       // (DefaultTableModel) ClientTbl.getModel(); 

    /**
     * Creates new form MonthlyClientReportFrame
     */
    public MonthlyClientReportInfoFrame() {
        initComponents();
         model =(DefaultTableModel) ClientTbl.getModel(); 
        File f= new File("Contract.txt");
        try 
        {
            Scanner s = new Scanner(f);
           
            String input2;
            String [] clientDetails;
   
            while(s.hasNextLine()){
                input2 = s.nextLine();
                clientDetails= input2.split(",");
                    model.addRow(new Object[]{clientDetails[1],clientDetails[0],clientDetails[11]});
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Operation Denied", " Confiration Message", JOptionPane.WARNING_MESSAGE);
        }
    }
    public Object geTtable(){return ClientTbl;
};
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        generateReportBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientTbl = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        generateReportBtn.setText("Generate Report");
        generateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportBtnActionPerformed(evt);
            }
        });

        ClientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Name", "Client ID", "No. of Staff Assigned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClientTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateReportBtn)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generateReportBtn)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) ClientTbl.getModel();
        ArrayList<String> arr=new ArrayList<String>();  
        for(int i=0;i<model.getRowCount();i++){
            String s="";
            for(int j=0;j<model.getColumnCount();j++)
            {
                s+=model.getValueAt(i, j);
                if(j<model.getColumnCount()-1)
                {
                    s+=",";
                }
            }
            arr.add(s);
            System.out.println(s);
        }
        ClientReport g=new ClientReport();
        JFreeChart x=g.generateChart(arr);
        ClientReportFrame F= new ClientReportFrame(x);
        F.setVisible(true);
        this.dispose(); 

        
    }//GEN-LAST:event_generateReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientTbl;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
