package framePkg;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NotificationFrame extends javax.swing.JFrame {
    FileReader fr=null;
    BufferedReader br=null;
     FileReader fr_additional=null;
    BufferedReader br_additional=null;
    String s =null;
ArrayList<String> id = new ArrayList();
ArrayList<String> name = new ArrayList();
ArrayList<String> feedback = new ArrayList();
ArrayList<String> line = new ArrayList();
int count =0;
int count_for_additonal_staff = 0;
ArrayList<String> id_additional = new ArrayList();
ArrayList<String> name_additional = new ArrayList();
ArrayList<String> feedback_additional = new ArrayList();
ArrayList<String> line_additional = new ArrayList();




    /**
     * Creates new form NotificationFrame
     */
    public NotificationFrame() throws IOException {
        initComponents();
        MessagePanel.setVisible(false);
         populateCombo();
         MessagePanel1.setVisible(false);
         populateComboAdditional();
    }
    private void populateCombo(){
        File f = new File("feedback.txt");
        if(f.exists()){
            try {
                fr = new FileReader(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    br = new BufferedReader(fr);
   
            try {
                while ((s = br.readLine()) != null){
                    count +=1;
                    line.add(s);
                    String words[] = s.split(",");
                    idCombo.addItem(words[0]);
                    id.add(words[0]);
                    name.add(words[1]);
                    feedback.add(words[2]);
                    
                } 
            notificationCount.setText(String.valueOf(count));
            
            } catch (IOException ex) {
                Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    
        }
        
    }
    private void populateComboAdditional(){
        File f = new File("Additional_Staff.txt");
        if(f.exists()){
            try {
                fr_additional = new FileReader(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    br_additional = new BufferedReader(fr_additional);
   
            try {
                while ((s = br_additional.readLine()) != null){
                    count_for_additonal_staff +=1;
                    line_additional.add(s);
                    String words[] = s.split(",");
                    additionalStaffIDCombo.addItem(words[0]);
                    id_additional.add(words[0]);
                    name_additional.add(words[1]);
                    feedback_additional.add(words[2]+" "+words[3]);
                    
                } 
                AdditionalnotificationCount1.setText(String.valueOf(count_for_additonal_staff));

            } catch (IOException ex) {
                Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MessagePanel = new javax.swing.JPanel();
        messageNotification = new javax.swing.JLabel();
        messageLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        openBtn = new javax.swing.JButton();
        idCombo = new javax.swing.JComboBox<>();
        notificationCount = new javax.swing.JLabel();
        clearAllBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AdditionalnotificationCount1 = new javax.swing.JLabel();
        additionalStaffIDCombo = new javax.swing.JComboBox<>();
        AdditionalStaffopenBtn = new javax.swing.JButton();
        clearAllBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MessagePanel1 = new javax.swing.JPanel();
        messageNotification1 = new javax.swing.JLabel();
        AdditionalmessageLbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AdditionalnameLbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdditionalidLbl1 = new javax.swing.JLabel();
        AdditionalClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notification Frame");

        jLabel1.setText("Notifications:");

        MessagePanel.setBackground(new java.awt.Color(255, 255, 204));

        messageNotification.setText("Message:");

        jLabel2.setText("Name ");

        jLabel4.setText("ID");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageNotification)
                    .addGroup(MessagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLbl)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(idLbl)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameLbl)
                    .addComponent(jLabel4)
                    .addComponent(idLbl))
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MessagePanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(clearBtn))
                    .addGroup(MessagePanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(messageNotification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        openBtn.setText("Open");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        notificationCount.setText("0");

        clearAllBtn.setText("Clear All");
        clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Additional Staff Request");

        AdditionalnotificationCount1.setText("0");

        AdditionalStaffopenBtn.setText("Open");
        AdditionalStaffopenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionalStaffopenBtnActionPerformed(evt);
            }
        });

        clearAllBtn1.setText("Clear All");
        clearAllBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        MessagePanel1.setBackground(new java.awt.Color(255, 255, 204));

        messageNotification1.setText("Message:");

        jLabel5.setText("Name ");

        jLabel6.setText("ID");

        AdditionalClearBtn.setText("Clear");
        AdditionalClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionalClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MessagePanel1Layout = new javax.swing.GroupLayout(MessagePanel1);
        MessagePanel1.setLayout(MessagePanel1Layout);
        MessagePanel1Layout.setHorizontalGroup(
            MessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdditionalmessageLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(AdditionalClearBtn)
                .addContainerGap())
            .addGroup(MessagePanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(MessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageNotification1)
                    .addGroup(MessagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdditionalnameLbl1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(AdditionalidLbl1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MessagePanel1Layout.setVerticalGroup(
            MessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AdditionalnameLbl1)
                    .addComponent(jLabel6)
                    .addComponent(AdditionalidLbl1))
                .addGroup(MessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MessagePanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(AdditionalClearBtn))
                    .addGroup(MessagePanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(messageNotification1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdditionalmessageLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(clearAllBtn))
                            .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(additionalStaffIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AdditionalnotificationCount1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(notificationCount)
                                    .addGap(15, 15, 15)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearAllBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdditionalStaffopenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MessagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MessagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(notificationCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearAllBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AdditionalnotificationCount1))
                .addGap(18, 18, 18)
                .addComponent(additionalStaffIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdditionalStaffopenBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearAllBtn1)
                .addGap(93, 93, 93))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
       
     
           String ido= idCombo.getSelectedItem().toString();
       
        int id_location = id.indexOf(ido);
        messageLbl.setText(feedback.get(id_location));
        nameLbl.setText(name.get(id_location));
        idLbl.setText(id.get(id_location));
        MessagePanel.setVisible(true);
                 

        
        
        
    }//GEN-LAST:event_openBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
       
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("feedback.txt");
            bw = new BufferedWriter(fw);
            int delete = id.indexOf(idCombo.getSelectedItem().toString());
            line.remove(delete);
            id.remove(delete);
            name.remove(delete);
            feedback.remove(delete);
            idCombo.removeItemAt(delete);
            messageLbl.setText("");
        nameLbl.setText("");
        idLbl.setText("");
            for(String s: line){
           bw.write(s+"\n");
            }
           bw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed
        // TODO add your handling code here:
             FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("feedback.txt");
            bw = new BufferedWriter(fw);
            int delete = id.indexOf(idCombo.getSelectedItem().toString());
            line.removeAll(line);
            id.removeAll(id);
            name.removeAll(name);
            feedback.removeAll(feedback);
            idCombo.removeAllItems();
            messageLbl.setText("");
        nameLbl.setText("");
        idLbl.setText("");
            for(String s: line){
           bw.write(s+"\n");
           
            }
           bw.close();
                       JOptionPane.showMessageDialog(null,"All notification cleared");

        } catch (Exception ex) {
            //Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_clearAllBtnActionPerformed

    private void AdditionalStaffopenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionalStaffopenBtnActionPerformed
        // TODO add your handling code here:
        
           String ido= additionalStaffIDCombo.getSelectedItem().toString();
       
        int id_location = id_additional.indexOf(ido);
        AdditionalmessageLbl1.setText(feedback_additional.get(id_location));
        AdditionalnameLbl1.setText(name_additional.get(id_location));
        AdditionalidLbl1.setText(id_additional.get(id_location));
        MessagePanel1.setVisible(true);
                 

        
        
        
    }//GEN-LAST:event_AdditionalStaffopenBtnActionPerformed

    private void clearAllBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtn1ActionPerformed
        // TODO add your handling code here:
                  FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("Additional_Staff.txt");
            bw = new BufferedWriter(fw);
            int delete = id_additional.indexOf(additionalStaffIDCombo.getSelectedItem().toString());
            line_additional.removeAll(line_additional);
            id_additional.removeAll(id_additional);
            name_additional.removeAll(name_additional);
            feedback_additional.removeAll(feedback_additional);
            additionalStaffIDCombo.removeAllItems();
            AdditionalmessageLbl1.setText("");
        AdditionalnameLbl1.setText("");
        AdditionalidLbl1.setText("");
            for(String s: line_additional){
           bw.write(s+"\n");
           
            }
           bw.close();
                       JOptionPane.showMessageDialog(null,"All AdditonalFrameFile cleared");

        } catch (Exception ex) {
            //Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_clearAllBtn1ActionPerformed

    private void AdditionalClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionalClearBtnActionPerformed
        // TODO add your handling code here:
                      FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("Additional_Staff.txt");
            bw = new BufferedWriter(fw);
            int delete = id_additional.indexOf(additionalStaffIDCombo.getSelectedItem().toString());
            line_additional.remove(delete);
            id_additional.remove(delete);
            name_additional.remove(delete);
            feedback_additional.remove(delete);
            additionalStaffIDCombo.removeItem(additionalStaffIDCombo.getSelectedItem().toString());
            AdditionalmessageLbl1.setText("");
        AdditionalnameLbl1.setText("");
        AdditionalidLbl1.setText("");
            for(String s: line_additional){
           bw.write(s+"\n");
           
            }
           bw.close();
                       JOptionPane.showMessageDialog(null,"All AdditonalFrameFile cleared");

        } catch (Exception ex) {
            //Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_AdditionalClearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NotificationFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NotificationFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionalClearBtn;
    private javax.swing.JButton AdditionalStaffopenBtn;
    private javax.swing.JLabel AdditionalidLbl1;
    private javax.swing.JLabel AdditionalmessageLbl1;
    private javax.swing.JLabel AdditionalnameLbl1;
    private javax.swing.JLabel AdditionalnotificationCount1;
    private javax.swing.JPanel MessagePanel;
    private javax.swing.JPanel MessagePanel1;
    private javax.swing.JComboBox<String> additionalStaffIDCombo;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JButton clearAllBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JLabel messageNotification;
    private javax.swing.JLabel messageNotification1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel notificationCount;
    private javax.swing.JButton openBtn;
    // End of variables declaration//GEN-END:variables
}
