package framePkg;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ShowContractsFrame extends javax.swing.JFrame {
FileReader fr=null;
BufferedReader br=null;
String s = null;
String n="";
    /**
     * Creates new form ContractsFrame
     */
    public ShowContractsFrame() {
        initComponents();
        ContractPanel.setVisible(false);
    }
    public ShowContractsFrame(String name, String data) {
        initComponents();
        if(name.equals("Client")){
        ContractPanel.setVisible(true);
        componenets();
        setDataClient(data);

        }
    }
    private void componenets(){
    ClientTxtField.setVisible(false);
    searchBtn.setVisible(false);
    jLabel9.setVisible(false);
    loadBtn.setVisible(false);
    clientIdCombo.setVisible(false);
    selectbtn.setVisible(false);
    foundLabel.setVisible(false);
    
    };
    
    private void setDataClient(String data){
      String words[] = data.split(",");
        ClientNameLabel.setText(words[1]);
        endDateLabel.setText(words[8]);
        contractDetailsLabel.setText(words[6]);
        staffLabel.setText(words[10]);
        supervisorlabel.setText(words[9]);
    
    
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ClientTxtField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        ContractPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contractDetailsLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        ClientNameLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        staffLabel = new javax.swing.JLabel();
        supervisorlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clientIdCombo = new javax.swing.JComboBox<>();
        loadBtn = new javax.swing.JButton();
        selectbtn = new javax.swing.JButton();
        foundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contract Frame");

        jLabel1.setText("Client:");

        ClientTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientTxtFieldActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        ContractPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Contract with Client:");

        contractDetailsLabel.setText("Contract with terms and conditions will be shown here.");

        jLabel4.setText("Expires on:");

        endDateLabel.setText("dd/mm/yyyy");

        ClientNameLabel.setText("Client name");

        jLabel11.setText("Appointed Staff ID :");

        jLabel12.setText("Appointed Supervisor ID");

        staffLabel.setText("jLabel3");

        supervisorlabel.setText("jLabel5");

        javax.swing.GroupLayout ContractPanelLayout = new javax.swing.GroupLayout(ContractPanel);
        ContractPanel.setLayout(ContractPanelLayout);
        ContractPanelLayout.setHorizontalGroup(
            ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
            .addGroup(ContractPanelLayout.createSequentialGroup()
                .addComponent(contractDetailsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContractPanelLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endDateLabel)
                .addContainerGap())
            .addGroup(ContractPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContractPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(staffLabel))
                    .addGroup(ContractPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(supervisorlabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContractPanelLayout.setVerticalGroup(
            ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContractPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClientNameLabel))
                .addGap(9, 9, 9)
                .addGroup(ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endDateLabel))
                .addGap(45, 45, 45)
                .addComponent(contractDetailsLabel)
                .addGap(41, 41, 41)
                .addGroup(ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(staffLabel))
                .addGap(38, 38, 38)
                .addGroup(ContractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(supervisorlabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("OR");

        jLabel9.setText("Choose");

        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        selectbtn.setText("Select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });

        foundLabel.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClientTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loadBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(selectbtn))
                            .addComponent(clientIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(foundLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(ContractPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClientTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadBtn))
                .addGap(4, 4, 4)
                .addComponent(selectbtn)
                .addGap(37, 37, 37)
                .addComponent(foundLabel)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(ContractPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    
        // TODO add your handling code here:
        ContractPanel.setVisible(true);
       
File f = new File("Contract.txt");
if(f.exists()){
try{
fr = new FileReader(f);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
br = new BufferedReader(fr);
    try {
        while ((s = br.readLine()) != null){
        if(s.contains(ClientTxtField.getText())){
            n=s;
        String words[] = n.split(",");
        ClientNameLabel.setText(words[1]);
        endDateLabel.setText(words[8]);
        contractDetailsLabel.setText(words[6]);
        staffLabel.setText(words[10]);
        supervisorlabel.setText(words[9]);
        }
        
        }
    } catch (IOException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }

      ContractPanel.setVisible(true);
}
else{
foundLabel.setText("not found");

}


    }//GEN-LAST:event_searchBtnActionPerformed

    private void ClientTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientTxtFieldActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
File f = new File("Contract.txt");
if(f.exists()){
    try {
        fr = new FileReader(f);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
        br = new BufferedReader(fr);
    try {
        while ((s = br.readLine()) != null){
            String words[] = s.split(",");
            clientIdCombo.addItem(words[0]);
        }
    } catch (IOException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
else{
foundLabel.setText("not found");

}
        
        
    }//GEN-LAST:event_loadBtnActionPerformed

    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        // TODO add your handling code here:
        File f = new File("Contract.txt");
if(f.exists()){
try{
fr = new FileReader(f);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
br = new BufferedReader(fr);
    try {
        while ((s = br.readLine()) != null){
        if(s.contains(clientIdCombo.getSelectedItem().toString())){
            n=s;
        String words[] = n.split(",");
        ClientNameLabel.setText(words[1]);
        endDateLabel.setText(words[8]);
        contractDetailsLabel.setText(words[6]);
        staffLabel.setText(words[10]);
        supervisorlabel.setText(words[9]);
        }
        
        }
    } catch (IOException ex) {
        Logger.getLogger(ShowContractsFrame.class.getName()).log(Level.SEVERE, null, ex);
    }

ContractPanel.setVisible(true);
}
else{
foundLabel.setText("not found");

}

        
        
        
        
    }//GEN-LAST:event_selectbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowContractsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowContractsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowContractsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowContractsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowContractsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientNameLabel;
    private javax.swing.JTextField ClientTxtField;
    private javax.swing.JPanel ContractPanel;
    private javax.swing.JComboBox<String> clientIdCombo;
    private javax.swing.JLabel contractDetailsLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel foundLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectbtn;
    private javax.swing.JLabel staffLabel;
    private javax.swing.JLabel supervisorlabel;
    // End of variables declaration//GEN-END:variables
}
