package framePkg;

import classPkg_CC.Staff;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class StaffPanel extends javax.swing.JPanel {
FileReader fr = null;
    BufferedReader br = null;
    String s = null;
    String n = null;
String name=null;
String ido = "";
String ida ="";
Staff k = new Staff();
    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        
       
     // check();
    }
    
    public void check(){
   if(!k.validateTrainable(ida)){
   applyForTrainingProgramBtn.setVisible(false);
   
   }
   else{
   applyForTrainingProgramBtn.setVisible(true);
   
   }
  
   
   }
    public void setNameAndID(String id){
        File f = new File("Staff.txt");
        if(f.exists()){
        try {
            fr = new FileReader(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        br = new BufferedReader(fr);
        try {
            while ((s = br.readLine()) != null){
                
                if(s.contains(id)){
                    n=s;
                    String words[] = n.split(",");
                    ido = words[0];
                    
                     if(ido.equals(id)){
                        ida = words[0];
                    name = words[1];
                    }
                    
                    
                   
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        IDLabel.setText(ida);
        NameLbl.setText(name);
        }
        else{
        IDLabel.setText("");
        NameLbl.setText("");
        
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applyForTrainingProgramBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();

        applyForTrainingProgramBtn.setText("Apply For Training Programs");
        applyForTrainingProgramBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyForTrainingProgramBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        NameLbl.setText("jLabel2");

        jLabel3.setText("ID");

        IDLabel.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(applyForTrainingProgramBtn)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDLabel))
                .addGap(94, 94, 94)
                .addComponent(applyForTrainingProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applyForTrainingProgramBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyForTrainingProgramBtnActionPerformed
        // TODO add your handling code here:
     k.applyForTrainingProgram();
    }//GEN-LAST:event_applyForTrainingProgramBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JButton applyForTrainingProgramBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
