package framePkg;

import classPkg_CC.SuperViser;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class SuperviserPanel extends javax.swing.JPanel {
FileReader fr = null;
    BufferedReader br = null;
    String s = null;
    String n = null;
String name="";
String ido = "";
SuperViser su = new SuperViser();
    /**
     * Creates new form SupervisorPanel
     */
    public SuperviserPanel() {
        initComponents();
      // check();
    }
   public void check(){
   if(!su.validateTrainable(ido)){
   applyForTrainingBtn.setVisible(false);
   
   }
   else{
      applyForTrainingBtn.setVisible(true);

   
   }
   
   }
    
    
public void setNameAndID(String id){
        File f = new File("Superviser.txt");
        if(f.exists()){
        try {
            fr = new FileReader(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        br = new BufferedReader(fr);
        try {
            while ((s = br.readLine()) != null){
                
                if(s.contains(id)){
                    n=s;
                    String words[] = n.split(",");
                    ido = words[0];
                    name = words[1];
                   
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        idLabel.setText(ido);
        nameLbl.setText(name);
        }
        else{
        idLabel.setText("");
        nameLbl.setText("");
        
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateEmployeeInfoBtn = new javax.swing.JButton();
        employeeInfoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        applyForTrainingBtn = new javax.swing.JButton();

        updateEmployeeInfoBtn.setText("Update Employee Information");
        updateEmployeeInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeInfoBtnActionPerformed(evt);
            }
        });

        employeeInfoBtn.setText("Employee Information");
        employeeInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInfoBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("ID");

        applyForTrainingBtn.setText("Apply For Training Program");
        applyForTrainingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyForTrainingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nameLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(updateEmployeeInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(employeeInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(applyForTrainingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmployeeInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(applyForTrainingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateEmployeeInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeInfoBtnActionPerformed
        // TODO add your handling code here:
       su.updateEmployeeInfor();
    }//GEN-LAST:event_updateEmployeeInfoBtnActionPerformed

    private void employeeInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInfoBtnActionPerformed
        // TODO add your handling code here:
       su.viewEmployeeInfo();
    }//GEN-LAST:event_employeeInfoBtnActionPerformed

    private void applyForTrainingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyForTrainingBtnActionPerformed
        // TODO add your handling code here:
        
        
        su.applyForTrainingProgram();
        
    }//GEN-LAST:event_applyForTrainingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyForTrainingBtn;
    private javax.swing.JButton employeeInfoBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton updateEmployeeInfoBtn;
    // End of variables declaration//GEN-END:variables
}
